name = "mc.ewpratten.com client"
author = "Evan Pratten"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.11.2"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2"]
no-internal-hashes = true
